TrainingApp.MVC.UI.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainingApp.MVC.UI.Process.Interfaces;
using TrainingApp.MVC.ViewModel;

namespace TrainingApp.MVC.UI.Web.Controllers
{
    public class ContactController : Controller
    {
        private readonly IUserProcess _userProcess;
        public ContactController(IUserProcess userProcess)
        {
            _userProcess = userProcess;
        }
        // GET: Contact
        public ActionResult Index()
        {
            var contactList = _userProcess.GetContactList();
            return View(contactList);
        }

        public ActionResult Detail(int Id)
        {
            var contactList = _userProcess.GetContactDetail(Id);
            return View("ContactDetailView", contactList);
        }

        [HttpGet]
        public ActionResult Edit(string status, int id, int userId)
        {
            Debug.WriteLine($"{status} {id} {userId}");
            var editTaskVM = new EditTaskVM
            {
                TaskId = id,
                Status = status,
                UserId = userId
            };
            _userProcess.EditTaskStatus(editTaskVM);
            return RedirectToAction("Detail", new { Id = editTaskVM.UserId });
        }

        [Route("Sort/{sort}")]
        public ActionResult Sort(string sort)
        {
            var contactList = _userProcess.GetContactBySort(sort);
            return View("Index", contactList);
        }

        [HttpPost]
        public ActionResult AddContact(ContactVM viewModel, HttpPostedFileBase file)
        {
            var image = Image.FromStream(file.InputStream);
            
            Debug.WriteLine($"{file.ContentLength}");
            if (ModelState.IsValid)
            {
                TempData["onAddCourse"] = true;
                viewModel.AddContactVM.AvatarImageByte = ImageToByteArray(image);
                _userProcess.AddContact(viewModel);
                return RedirectToAction("Index");
            }
            TempData["onAddCourse"] = false;
            return RedirectToAction("Index");
        }

        [HttpPost]
        //[Route("AddTask")]
        public ActionResult AddTask(ContactDetailVM viewModel)
        {

            if (ModelState.IsValid)
            {
                _userProcess.AddTask(viewModel);
                return RedirectToAction("Detail", new { Id = viewModel.Id });
            }
            return RedirectToAction("Detail", new { Id = viewModel.Id });
        }



        public byte[] ImageToByteArray(Image imageIn)
        {
            using (var ms = new MemoryStream())
            {
                imageIn.Save(ms, imageIn.RawFormat);
                return ms.ToArray();
            }
        }


    }
}

TrainingApp.MVC.UI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrainingApp.MVC.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TrainingApp.MVC.UI.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestSharp;
using TrainingApp.MVC.Framework.Constants;
using TrainingApp.MVC.Framework.WebServices.Interfaces;
using TrainingApp.MVC.UI.Process.Interfaces;
using TrainingApp.MVC.ViewModel;

namespace TrainingApp.MVC.UI.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserProcess _userProcess;

        public UserController(IUserProcess userProcess)
        {
            _userProcess = userProcess;
        }

        // GET: User
        public ActionResult Index()
        {
            var data = _userProcess.Get(1);
            //Debug.WriteLine(data.CourseVMList[0].CourseName);
            return View(data);
        }

        [HttpPost]
        public ActionResult AddCourse(UserVM viewModel)
        {
            if (ModelState.IsValid)
            {
                TempData["onAddCourse"] = true;
                _userProcess.AddCourse(viewModel);
                return RedirectToAction("Index");
            }
            TempData["onAddCourse"] = false;
            return RedirectToAction("Index");
        }


    }

}

TrainingApp.MVC.UI.Web/Views/Contact/AddContactModal.cshtml
@model ContactVM
@{ 
    var selectListItem =  new List<SelectListItem>();
    selectListItem.Add(new SelectListItem
    {
        Text = "Select Category",
        Value = null,
        Selected = true
    });
    selectListItem.Add(new SelectListItem
    {
        Text = "Manager",
        Value = "Manager"
    });

    selectListItem.Add(new SelectListItem
    {
        Text = "Developer",
        Value = "Developer"
    });
    selectListItem.Add(new SelectListItem
    {
        Text = "Designer",
        Value = "Designer"
    });

    IEnumerable<SelectListItem> selectedListCategory = selectListItem;

}
<div class="modal fade add-contact-modal" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content  pt-2 pl-3 pr-3 pb-3">
            <div class="modal-header" style="margin-left:-1rem;">
                <h5 class="modal-title" style="font-size:14px;">Create New Contact</h5>
                <button type="button" class="close" id="close-addpatient-modal" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("AddContact", "Contact", FormMethod.Post, new { id = "AddContactForm", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
        <div class="mt-3 mb-3 d-flex justify-content-center" id="image-uploader-div">
            <input type="file" id="image-uploader-input" name="file" style="display:none;" />

            <div class="d-flex justify-content-center w-25 h-25 p-3" style="background-color:aliceblue; border-radius:10px;">
                <i class="fa fa-3x fa-user-circle" id="user-icon-i" style="color:deepskyblue;"></i>
                <img id="imgPreview" alt="pic" style="width:100px;height:100px; display:none;" />
            </div>
        </div>
                <div class="row mt-2">
                    <div class="form-group col">
                        <label for="InputNRIC">First Name<span style="color:red">*</span></label>
                        @Html.EditorFor(model => model.AddContactVM.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AddContactVM.FirstName, String.Empty, new { @class = "text-danger" })
                    </div>
                    <div class="form-group col">
                        <label for="InputFullName">Last Name<span style="color:red">*</span></label>
                        @Html.EditorFor(model => model.AddContactVM.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AddContactVM.LastName, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group mt-2">
                    <label for="InputNRIC">Email<span style="color:red">*</span></label>
                    @Html.EditorFor(model => model.AddContactVM.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "eg. chenthye0825@hotmail.com", @style = "max-width:100%;" } })
                    @Html.ValidationMessageFor(model => model.AddContactVM.Email, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })
                </div>
                <div class="row">
                    <div class="form-group col">
                        <label for="InputPhoneNumber">Phone Number<span style="color:red">*</span></label>
                        @Html.EditorFor(model => model.AddContactVM.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "eg. 018-123456789" } })
                        @Html.ValidationMessageFor(model => model.AddContactVM.PhoneNumber, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })
                    </div>
                    <div class="form-group col">
                        <label for="InputGender">Category<span style="color:red">*</span></label>
                        @Html.DropDownListFor(model => model.AddContactVM.Category, selectedListCategory, new { @class = "custom-select form-control", @placeholder = "eg. Select Category" })
                        @Html.ValidationMessageFor(model => model.AddContactVM.Category, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-6">
                        <label for="InputPhoneNumber">Salary Rate/Hr<span style="color:red">*</span></label>
                        @Html.EditorFor(model => model.AddContactVM.HourRate, new { htmlAttributes = new { @class = "form-control", @placeholder = "eg. 17/Hr" } })
                        @Html.ValidationMessageFor(model => model.AddContactVM.HourRate, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })
                    </div>
                </div>
                <hr />
                <div class="modal-footer">
                    <button class="btn btn-light mr-auto px-3 py-2">Cancel</button>
                    <button type="submit" class="btn" style="background: #8173FE; color:white;">Add Contact</button>
                </div>
            }
        </div>
    </div>
</div>

TrainingApp.MVC.UI.Web/Views/Contact/AddTaskModal.cshtml
@model ContactDetailVM
@{
    var selectListItem = new List<SelectListItem>();
    selectListItem.Add(new SelectListItem
    {
        Text = "Select task status",
        Value = null,
        Selected = true
    });
    selectListItem.Add(new SelectListItem
    {
        Text = "On Hold",
        Value = "On Hold"
    });

    selectListItem.Add(new SelectListItem
    {
        Text = "Pending",
        Value = "Pending"
    });
    selectListItem.Add(new SelectListItem
    {
        Text = "Done",
        Value = "Done"
    });

    IEnumerable<SelectListItem> selectedListCategory = selectListItem;

}
<div class="modal fade add-task-modal" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content  pt-2 pl-3 pr-3 pb-3">
            <div class="modal-header" style="margin-left:-1rem;">
                <h5 class="modal-title" style="font-size:14px;">Create New Task</h5>
                <button type="button" class="close" id="close-addpatient-modal" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("AddTask", "Contact", FormMethod.Post, new { id = "AddTaskForm"}))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-group col">
                        <label for="InputPhoneNumber">Task Name<span style="color:red">*</span></label>
                        @Html.HiddenFor(c=>c.Id)
                        @Html.EditorFor(model => model.AddTask.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AddTask.TaskName, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })
                    </div>
                    <div class="form-group col">
                        <label for="InputGender">Task Status<span style="color:red">*</span></label>
                        @Html.DropDownListFor(model => model.AddTask.TaskStatus, selectedListCategory, new { @class = "custom-select form-control", @placeholder = "eg. Select Task Status" })
                        @Html.ValidationMessageFor(model => model.AddTask.TaskStatus, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })
                    </div>
                </div>
                <hr />
                <div class="modal-footer">
                    <button class="btn btn-light mr-auto px-3 py-2">Cancel</button>
                    <button type="submit" class="btn" style="background: #8173FE; color:white;">Add Task</button>
                </div>
            }
        </div>
    </div>
</div>

TrainingApp.MVC.UI.Web/Views/Contact/ContactDetailView.cshtml
@model ContactDetailVM

@Styles.Render("~/contact/css")
<div class="container-fluid">
    <div class="row ">
        <div class="left-side col-md-2 bg-white border-right" style="min-height:100vh;">
            <div class="top-of-left d-flex flex-row mt-2 ml-2">
                @if (Model.AvatarImageByte != null)
                {
                    <img class="profile-pic rounded" src="data:image;base64,@System.Convert.ToBase64String(Model.AvatarImageByte)" style="width:55px;height:45px;" alt="name" />

                }
                else
                {
                    <img class="profile-pic rounded"  style="width:55px;height:45px;" alt="name" />

                }
                <div class="beside-profile-pic d-flex flex-column ml-1 pl-2 pt-1" style="font-weight:400; font-size:0.8rem;">
                    <div class="profile-name">@String.Concat($"{Model.FirstName + " " + Model.LastName}")</div>
                    <p class="profile-category">@Model.Category</p>
                </div>
            </div>
            <hr />
            <div class="d-flex flex-column mt-md-5 mt-3">
                <div class="con-detail-label" style="font-weight:600; font-size:0.8rem;">Contact Details</div>
                <div class="cont-info-group" style="font-weight:400; font-size:0.8rem;">
                    <div class="profile-email">@Model.Email</div>
                    <div class="profile-email">@Model.PhoneNumber</div>
                </div>
            </div>

            <div class="d-flex flex-column mt-md-5 mt-3">
                <div class="con-detail-label" style="font-weight:600; font-size:0.8rem;">Hourly Rate</div>
                <div class="cont-info-group" style="font-weight:400; font-size:0.8rem;">
                    <div class="profile-email"><span class="font-weight-bold">@Model.HourRate</span>/hr</div>
                </div>
            </div>

            <div class="d-flex flex-column mt-md-5 mt-3">
                <div class="con-detail-label" style="font-weight:600; font-size:0.8rem;">Category/Role</div>
                <div class="cont-category-group" style="font-weight:400; font-size:0.8rem;">
                    <div class="profile-email p-2 rounded d-inline-flex" style="background: #F8F8FF;">@Model.Category</div>
                </div>
            </div>
        </div>
        <div class="Right-side col-md-10">
            <div class="the-top-of-right">@Html.Partial("_topview",TempData["Header"]="Profile Overview")</div>
            <div class="below-top-view-big-ass-white-colour bg-white ml-3 mr-3 mb-3 p-3 contact-container" style="min-height:75vh;">
                <div class="d-flex add-task-btn">
                    <button class="btn" data-toggle="modal" data-target=".add-task-modal" style="background: #8173FE; color:white;">Add New Task</button>
                </div>
                @foreach (var n in Model.TaskList)
                {
                    <div class="card mt-3">
                        <div class="card-body">
                            <div class="inner-wrapper d-flex flex-row align-items-center">
                                <div class="task-name mr-auto">@n.TaskName</div>
                                <div class="task-status mr-md-4 p-2 rounded d-inline-flex" style="background: #F8F8FF;">@n.TaskStatus</div>
                                <div class="change-status-dot">
                                    <a class="float-right" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" style="cursor:pointer;" aria-expanded="false">
                                        <i class="fa fa-ellipsis-v"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                        @if (n.TaskStatus == "On Hold")
                                        {
                                            <a class="dropdown-item" href="/Contact/Edit/?status=Pending&id=@n.Id&userId=@Model.Id" id="edit-btn">Pending</a>
                                            <a class="dropdown-item" href="/Contact/Edit/?status=Done&id=@n.Id&userId=@Model.Id" id="edit-btn">Done</a>

                                        }
                                        @if (n.TaskStatus == "Pending")
                                        {
                                            <a class="dropdown-item" href="/Contact/Edit/?status=On Hold&id=@n.Id&userId=@Model.Id" id="edit-btn">On Hold</a>
                                            <a class="dropdown-item" href="/Contact/Edit/?status=Done&id=@n.Id&userId=@Model.Id" id="edit-btn">Done</a>
                                        }
                                        @if (n.TaskStatus == "Done")
                                        {
                                            <a class="dropdown-item" href="/Contact/Edit/?status=On Hold&id=@n.Id&userId=@Model.Id" id="edit-btn">On Hold</a>
                                            <a class="dropdown-item" href="/Contact/Edit/?status=Pending&id=@n.Id&userId=@Model.Id" id="edit-btn">Pending</a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@Html.Partial("AddTaskModal", Model)

TrainingApp.MVC.UI.Web/Views/Contact/ContactEmptyView.cshtml
@model ContactVM

<div class="container">
    <div class="row  justify-content-center align-content-center">
        <p class="col-12 text-center">No Contact List Available</p>
        <div class="col-auto">
        <button class="btn" data-toggle="modal" data-target=".add-contact-modal" style="background: #8173FE; color:white;">Add Contact</button>
        </div>
    </div>
</div>

TrainingApp.MVC.UI.Web/Views/Contact/ContactListView.cshtml
@model ContactVM
<div class="bg-white ml-3 mr-3 mb-3 contact-container">
    <div class="container-fluid ml-3 mr-3 mt-3">
        <div class="row mt-3">
            <div class="col-8 d-flex justify-content-start align-items-center" id="btnContainer">
                <button class="btn active align-self-baseline mr-1" id="listViewBtn"><i class="fa fa-bars"></i> List</button>
                <button class="btn align-self-baseline" id="gridViewBtn"><i class="fa fa-th-large"></i> Grid</button>
                <div class="mb-3 ml-auto" id="btnContainer">
                    <button class="btn mr-2" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-filter" style="margin-right:0.1rem;"></i> Sort By
                        <i class="fa fa-chevron-down" style="margin-left:0.1rem;"></i>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="Contact/Sort/?sort=Name">Name</a>
                        <a class="dropdown-item" href="Contact/Sort/?sort=Category">Category</a>
                        <a class="dropdown-item" href="Contact/Sort/?sort=Salary">Hourly Rate</a>
                    </div>
                </div>
            </div>
        </div>


        <div class="row no-gutters" id="outer-row" style="margin-right:inherit;">
            @foreach(var n in Model.ContactVMList)
            {
                <a href="/Contact/Detail/@n.Id" class="card col-xl-8 col-md-12 co-sm-12 col-12  mb-3 no-gutters" style="text-decoration:none; color:inherit;">
                    <div class="card-body" style="font-size:12px; font-weight:500;">
                        <div class="no-padding row align-items-center">
                            <img class="profile-img mr-2" src="data:image;base64,@System.Convert.ToBase64String(n.AvatarImageByte)" style="width:55px;height:45px;" alt="name" />
                            <div class="profile-name col-lg-auto col-md-auto col-sm-auto col-auto font-weight-bold">@string.Concat($"{n.FirstName} {n.LastName}")</div>
                            <div class="profile-email col-lg-auto col-md-auto col-sm-auto col-auto">@n.Email</div>
                            <div class="profile-hpNumber col-lg-auto col-md-auto col-sm-auto col-auto">@n.PhoneNumber</div>
                            <div class="profile-hourlyRate mr-3 col-lg-auto col-md-auto col-sm-auto col-auto"><span style="font-weight:700;">$@n.HourRate</span><span>/hr</span></div>
                            <div class="bg-light p-2 profile-role col-lg-auto col-md-auto col-sm-auto col-auto" style="border-radius:0.5rem;">@n.Category</div>
                            <!--<div class="p-2 profile-dots col-xl-auto col-auto" style="border:solid 1px black; border-radius:8px;"><i class="fa fa-ellipsis-h"></i></div>-->
                        </div>
                    </div>
                </a>
            }
        </div>
    </div>
    @Html.Partial("contactPagination", Model)
</div>

TrainingApp.MVC.UI.Web/Views/Contact/Index.cshtml
@model ContactVM
@{
    ViewBag.Title = "Index";
}

@Styles.Render("~/contact/css")
@Html.Partial("_topview",TempData["Header"] = "Contacts")

@if (Model.ContactVMList.Count <= 0)
{
    @Html.Partial("ContactEmptyView", Model)
}
else
{
    @Html.Partial("ContactListView", Model)

}
@Html.Partial("AddContactModal", Model)

@section Scripts
{
    <script>
        var outerRow = document.getElementById("outer-row");
        var listViewbtn = $('#listViewBtn');
        var gridViewbtn = $('#gridViewBtn');
        var imageUploaderDiv = document.getElementById("image-uploader-div");
        var imageUploaderInput = document.getElementById("image-uploader-input");
        const listColList = ["col-xl-8", "col-12", "co-sm-12", "col-md-12"];
        const gridColList = ["col-md-5"];
        // Grid View
        function gridView() {
            outerRow.className += " justify-content-around";

            $('#outer-row').find("a").each(function (index, obj) {
                console.log(index);
                $(this).removeClass(listColList).addClass(gridColList).css("margin-right", "0.1rem");
            })
        }
        function listView() {
            $('#outer-row').removeClass("justify-content-around");
            $('#outer-row').find("a").each(function (index, obj) {
                console.log(index);
                $(this).removeClass(gridColList).addClass(listColList);
            })
        }
        listViewbtn.click(function (e) {
            e.preventDefault();
            listView();
        })

        gridViewbtn.click(function (e) {
            e.preventDefault();
            gridView();
        })

        imageUploaderDiv.addEventListener("click", openInputFile);
        function openInputFile() {
            imageUploaderInput.click();
        };

        $('#image-uploader-input').change(function () {
            const file = this.files[0];
            console.log(file);
            if (file) {
                let reader = new FileReader();
                reader.onload = function (event) {
                    console.log(event.target.result);
                    $('#user-icon-i').css("display", "none");
                    $('#imgPreview').css("display", "initial");
                    $('#imgPreview').attr('src', event.target.result);
                }
                reader.readAsDataURL(file);
            }
        });


                    //var container = document.getElementById("btnContainer");
                    //var btns = container.getElementsByClassName("btn");
        /* for (var i = 0; i < btns.length; i++) {
             btns[i].addEventListener("click", function () {
                 var current = document.getElementsByClassName("active");
                 current[0].className = current[0].className.replace(" active", "");
                 this.className += " active";
             });*/
    </script>
}

TrainingApp.MVC.UI.Web/Views/Contact/contactPagination.cshtml
@model ContactVM
<nav class="mb-2" aria-label="Page navigation example">
    <div class="row">
        <ul class="col pagination justify-content-center">
            @if (Model.CurrentPage == 1 || Model.TotalPage == 1)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>

            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="#">Previous</a>
                </li>
            }
            @for (int i = 1; i <= Model.TotalPage; i++)
            {
                if (Model.CurrentPage == i)
                {
                    <li class="page-item active">
                        <a class="page-link" href="#">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link" href="#">@i</a>
                    </li>
                }
                
            }
            @if (Model.CurrentPage == 1 || Model.TotalPage == 1)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>

            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            }
        </ul>
        </div>
</nav>

TrainingApp.MVC.UI.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TrainingApp.MVC.UI.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TrainingApp.MVC.UI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TrainingApp.MVC.UI.Web/Views/User/AddCourseForm.cshtml
@model TrainingApp.MVC.ViewModel.UserVM


@using (Html.BeginForm("AddCourse", "User", FormMethod.Post, new { id = "AddCourseForm" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <input type="text" style="display:none;" class="form-control" id="onAddCourse" data-value="@TempData["onAddCourse"]">
        <label asp-for="Name" class="control-label"></label>
        @Html.EditorFor(model => model.AddCourseVM.CourseName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.AddCourseVM.CourseName, String.Empty, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="margin-bottom:10px;">
        <label asp-for="Country" class="control-label"></label>
        @Html.EditorFor(model => model.AddCourseVM.Grade, new { htmlAttributes = new { id = "GradeInput", @class = "form-control Grade" } })
        @Html.ValidationMessageFor(model => model.AddCourseVM.Grade, String.Empty, new { id = "GradeInputErr", @class = "text-danger" })
        @Html.HiddenFor(c => c.Id)
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary pull-left" onclick="return isValid()">Save</button>
        <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-primary pull-left">Cancel</button>
    </div>


}